language: node_js
node_js:
 - '10'
env:
  global:
    - CI_API = true
    - CI_APP = true
  directories:
    - api/node_modules
    - app/node_modules  
  cache:
    directories:
      - api/node_modules
      - app/node_modules
  branches:
    only:
      - master
    
install:
  - bash install.sh
script:
  - bash run.sh