language: node_js
node_js:
 - '10'
env:
  global:
    - CI_API = true
    - CI_APP = true
  directories:
    - api/node_modules
    - app/node_modules  
  cache:
    directories:
      - api/node_modules
      - app/node_modules
  branches:
    only:
      - master
before_install:
 - echo $CI_API
 - echo CI_APP
install:
  - | 
    if [ $CI_API == true ]; then 
      cd "$TRAVIS_BUILD_DIR/api" && npm i; 
    fi
  - | 
    if [ $CI_APP == true ]; then 
      cd "$TRAVIS_BUILD_DIR/app" && npm i; 
    fi
script:
  - | 
    if [ $CI_API == true ]; then 
      cd "$TRAVIS_BUILD_DIR/api" && npm t; 
    fi
  - | 
    if [ $CI_APP == true ]; then 
      cd "$TRAVIS_BUILD_DIR/app" && npm t; 
    fi